# server
server:
  port: 8889

# profile
spring:
  profiles:
    active: local
  shiro:
    login-url: /login
    success-url: /
    unauthorized-url: /403
    filter-chain-definition-map:
      anon: /static/**,/BJUI/**,/favicon.ico,/timeout,/test/**,/lang=en_US,/lang=zh_CN
      authc: /authc
      logout: /exit
      user: /**
logging:
  config: classpath:logging-config.xml





